# Generated by Django 3.2.8 on 2024-06-07 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.UUIDField()),
                ('coin', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
