# Generated by Django 3.2.8 on 2024-06-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingtask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
